version: '2.0'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongo
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo